# Generated by Django 5.2.5 on 2026-02-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Особенность товара',
                'verbose_name_plural': 'Особенности товаров',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='flavor',
            field=models.CharField(blank=True, choices=[('neutral', 'Нейтральный'), ('banana', 'Банан'), ('strawberry', 'Клубника'), ('chocolate', 'Шоколад'), ('mint', 'Мята'), ('vanilla', 'Ваниль')], max_length=20, verbose_name='Аромат'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена (₽)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (₽)'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_in_pack',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество в упаковке'),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Например: 0.02', max_digits=4, null=True, verbose_name='Толщина (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, choices=[('CN', 'Китай'), ('JP', 'Япония'), ('DE', 'Германия'), ('MY', 'Малайзия'), ('TH', 'Таиланд'), ('IN', 'Индия'), ('KR', 'Южная Корея')], max_length=5, verbose_name='Страна производства'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('latex', 'Натуральный латекс'), ('polyurethane', 'Полиуретан'), ('polyisoprene', 'Полиизопрен')], max_length=20, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена (₸)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (₸)'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.productfeature', verbose_name='Особенности'),
        ),
    ]
