# Generated by Django 5.2.5 on 2026-02-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productfeature_product_flavor_product_old_price_rub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Аромат',
                'verbose_name_plural': 'Ароматы',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='product',
            name='background',
            field=models.ImageField(blank=True, help_text='Фоновое изображение товара', upload_to='products/backgrounds/', verbose_name='Фон'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='length_mm',
            field=models.PositiveIntegerField(default=0, help_text='Длина, например: 180', verbose_name='Длина (мм)'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='width_mm',
            field=models.PositiveIntegerField(default=0, help_text='Номинальная ширина, например: 52', verbose_name='Ширина (мм)'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavors',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.flavor', verbose_name='Ароматы'),
        ),
    ]
