# Generated by Django 5.2.5 on 2026-02-15 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_flavor_remove_product_flavor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('value_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('predefined', 'Предопределённые значения')], default='text', max_length=20, verbose_name='Тип значения')),
                ('unit', models.CharField(blank=True, help_text='мм, шт, мл, мес', max_length=20, verbose_name='Единица измерения')),
                ('is_multi', models.BooleanField(default=False, help_text='Можно выбрать несколько значений (для predefined)', verbose_name='Множественный выбор')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='background',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country_of_origin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_contents',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_pack',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shelf_life_months',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thickness_mm',
        ),
        migrations.CreateModel(
            name='CategoryCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательная (для фильтров)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_characteristics', to='catalog.category', verbose_name='Категория')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_bindings', to='catalog.characteristic', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика категории',
                'verbose_name_plural': 'Характеристики категорий',
                'ordering': ['order'],
                'unique_together': {('category', 'characteristic')},
            },
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('background', models.ImageField(blank=True, help_text='Фоновое изображение (например для ароматов)', upload_to='characteristics/backgrounds/', verbose_name='Фон')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_values', to='catalog.characteristic', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристик',
                'ordering': ['order', 'name'],
                'unique_together': {('characteristic', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=500, verbose_name='Текстовое значение')),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Числовое значение')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='catalog.characteristic', verbose_name='Характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog.product', verbose_name='Товар')),
                ('values', models.ManyToManyField(blank=True, to='catalog.characteristicvalue', verbose_name='Предопределённые значения')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товаров',
                'ordering': ['characteristic__order'],
                'unique_together': {('product', 'characteristic')},
            },
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
        migrations.DeleteModel(
            name='ProductFeature',
        ),
    ]
