# Generated by Django 5.2.5 on 2026-02-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_characteristic_remove_product_flavors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='display_inline',
            field=models.BooleanField(default=False, help_text='Название – значение в одну строку', verbose_name='В одну строку'),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='hint_text',
            field=models.CharField(blank=True, help_text='Текст рядом с значением, например: (тоньше волоса)', max_length=200, verbose_name='Вспомогательный текст'),
        ),
    ]
