# Generated by Django 5.2.5 on 2026-02-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_characteristic_display_inline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='display_inline',
        ),
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='hint_text',
        ),
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='value_number',
        ),
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='value_text',
        ),
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='values',
        ),
        migrations.AddField(
            model_name='categorycharacteristic',
            name='display_mode',
            field=models.CharField(choices=[('block', 'Блок'), ('inline', 'В строку')], default='block', max_length=10, verbose_name='Отображение'),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='hint',
            field=models.CharField(blank=True, help_text='(тоньше волоса)', max_length=200, verbose_name='Подсказка'),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='selected_values',
            field=models.ManyToManyField(blank=True, help_text='Для predefined типа', to='catalog.characteristicvalue', verbose_name='Выбранные значения'),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='value',
            field=models.CharField(blank=True, help_text='Для text/number типов', max_length=500, verbose_name='Значение'),
        ),
    ]
